// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type TenantConv struct {
	ConvID        int64
	TenantID      int64
	Title         string
	Status        string
	TotalTokens   int64
	ModelID       string
	ModelProvider string
	CreatedAt     int64
	UpdatedAt     int64
}

type TenantInfo struct {
	TenantID  int64
	Info      string
	CreatedAt int64
	UpdatedAt int64
}

type UserTenant struct {
	UserID    string
	TenantID  int64
	CreatedAt int64
}
