// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_info.sql

package store

import (
	"context"
)

const getTenantInfo = `-- name: GetTenantInfo :one
SELECT tenant_id, info, created_at, updated_at FROM tenant_info WHERE tenant_id = ?
`

func (q *Queries) GetTenantInfo(ctx context.Context, tenantID int64) (TenantInfo, error) {
	row := q.db.QueryRowContext(ctx, getTenantInfo, tenantID)
	var i TenantInfo
	err := row.Scan(
		&i.TenantID,
		&i.Info,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantInfo = `-- name: UpdateTenantInfo :exec
UPDATE tenant_info
SET info = ?, updated_at = strftime('%s', 'now')
WHERE tenant_id = ?
`

type UpdateTenantInfoParams struct {
	Info     string
	TenantID int64
}

func (q *Queries) UpdateTenantInfo(ctx context.Context, arg UpdateTenantInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantInfo, arg.Info, arg.TenantID)
	return err
}

const upsertTenantInfo = `-- name: UpsertTenantInfo :exec
INSERT INTO tenant_info (tenant_id, info, created_at, updated_at)
VALUES (?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
ON CONFLICT(tenant_id) DO UPDATE SET
    info       = excluded.info,
    updated_at = excluded.updated_at
`

type UpsertTenantInfoParams struct {
	TenantID int64
	Info     string
}

func (q *Queries) UpsertTenantInfo(ctx context.Context, arg UpsertTenantInfoParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenantInfo, arg.TenantID, arg.Info)
	return err
}
