// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_conv.sql

package store

import (
	"context"
)

const createTenantConv = `-- name: CreateTenantConv :one
INSERT INTO tenant_conv (tenant_id, title, total_tokens, model_id, model_provider, status, created_at, updated_at)
VALUES (?, ?, 0, '', '', 'active', strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING conv_id
`

type CreateTenantConvParams struct {
	TenantID int64
	Title    string
}

func (q *Queries) CreateTenantConv(ctx context.Context, arg CreateTenantConvParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTenantConv, arg.TenantID, arg.Title)
	var conv_id int64
	err := row.Scan(&conv_id)
	return conv_id, err
}

const getLatestActiveTenantConv = `-- name: GetLatestActiveTenantConv :one
SELECT conv_id, tenant_id, title, status, total_tokens, model_id, model_provider, created_at, updated_at FROM tenant_conv
WHERE tenant_id = ? AND status = 'active'
ORDER BY conv_id DESC
LIMIT 1
`

func (q *Queries) GetLatestActiveTenantConv(ctx context.Context, tenantID int64) (TenantConv, error) {
	row := q.db.QueryRowContext(ctx, getLatestActiveTenantConv, tenantID)
	var i TenantConv
	err := row.Scan(
		&i.ConvID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.TotalTokens,
		&i.ModelID,
		&i.ModelProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantConv = `-- name: GetTenantConv :one
SELECT conv_id, tenant_id, title, status, total_tokens, model_id, model_provider, created_at, updated_at FROM tenant_conv WHERE conv_id = ?
`

func (q *Queries) GetTenantConv(ctx context.Context, convID int64) (TenantConv, error) {
	row := q.db.QueryRowContext(ctx, getTenantConv, convID)
	var i TenantConv
	err := row.Scan(
		&i.ConvID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.TotalTokens,
		&i.ModelID,
		&i.ModelProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incTenantConvUsage = `-- name: IncTenantConvUsage :exec
UPDATE tenant_conv
SET total_tokens   = total_tokens + ?,
    model_id       = ?,
    model_provider = ?,
    updated_at     = strftime('%s', 'now')
WHERE conv_id = ?
`

type IncTenantConvUsageParams struct {
	TotalTokens   int64
	ModelID       string
	ModelProvider string
	ConvID        int64
}

func (q *Queries) IncTenantConvUsage(ctx context.Context, arg IncTenantConvUsageParams) error {
	_, err := q.db.ExecContext(ctx, incTenantConvUsage,
		arg.TotalTokens,
		arg.ModelID,
		arg.ModelProvider,
		arg.ConvID,
	)
	return err
}

const listTenantConvsByTenant = `-- name: ListTenantConvsByTenant :many
SELECT conv_id, tenant_id, title, status, total_tokens, model_id, model_provider, created_at, updated_at FROM tenant_conv
WHERE tenant_id = ?
ORDER BY conv_id ASC
`

func (q *Queries) ListTenantConvsByTenant(ctx context.Context, tenantID int64) ([]TenantConv, error) {
	rows, err := q.db.QueryContext(ctx, listTenantConvsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantConv{}
	for rows.Next() {
		var i TenantConv
		if err := rows.Scan(
			&i.ConvID,
			&i.TenantID,
			&i.Title,
			&i.Status,
			&i.TotalTokens,
			&i.ModelID,
			&i.ModelProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantConvsByTenantAndStatus = `-- name: ListTenantConvsByTenantAndStatus :many
SELECT conv_id, tenant_id, title, status, total_tokens, model_id, model_provider, created_at, updated_at FROM tenant_conv
WHERE tenant_id = ? AND status = ?
ORDER BY conv_id ASC
`

type ListTenantConvsByTenantAndStatusParams struct {
	TenantID int64
	Status   string
}

func (q *Queries) ListTenantConvsByTenantAndStatus(ctx context.Context, arg ListTenantConvsByTenantAndStatusParams) ([]TenantConv, error) {
	rows, err := q.db.QueryContext(ctx, listTenantConvsByTenantAndStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantConv{}
	for rows.Next() {
		var i TenantConv
		if err := rows.Scan(
			&i.ConvID,
			&i.TenantID,
			&i.Title,
			&i.Status,
			&i.TotalTokens,
			&i.ModelID,
			&i.ModelProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantConvStatus = `-- name: UpdateTenantConvStatus :exec
UPDATE tenant_conv
SET status = ?, updated_at = strftime('%s', 'now')
WHERE conv_id = ?
`

type UpdateTenantConvStatusParams struct {
	Status string
	ConvID int64
}

func (q *Queries) UpdateTenantConvStatus(ctx context.Context, arg UpdateTenantConvStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantConvStatus, arg.Status, arg.ConvID)
	return err
}

const updateTenantConvUsage = `-- name: UpdateTenantConvUsage :exec
UPDATE tenant_conv
SET total_tokens = ?, model_id = ?, model_provider = ?, updated_at = strftime('%s', 'now')
WHERE conv_id = ?
`

type UpdateTenantConvUsageParams struct {
	TotalTokens   int64
	ModelID       string
	ModelProvider string
	ConvID        int64
}

func (q *Queries) UpdateTenantConvUsage(ctx context.Context, arg UpdateTenantConvUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantConvUsage,
		arg.TotalTokens,
		arg.ModelID,
		arg.ModelProvider,
		arg.ConvID,
	)
	return err
}
