// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_tenant.sql

package store

import (
	"context"
)

const createUserTenant = `-- name: CreateUserTenant :one
INSERT INTO user_tenant (user_id, tenant_id, created_at)
VALUES (
    ?,
    COALESCE((SELECT MAX(tenant_id) FROM user_tenant), 0) + 1,
    strftime('%s', 'now')
)
RETURNING tenant_id
`

func (q *Queries) CreateUserTenant(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUserTenant, userID)
	var tenant_id int64
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const getUserTenantByTenantID = `-- name: GetUserTenantByTenantID :one
SELECT user_id FROM user_tenant WHERE tenant_id = ?
`

func (q *Queries) GetUserTenantByTenantID(ctx context.Context, tenantID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserTenantByTenantID, tenantID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserTenantByUserID = `-- name: GetUserTenantByUserID :one
SELECT tenant_id FROM user_tenant WHERE user_id = ?
`

func (q *Queries) GetUserTenantByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserTenantByUserID, userID)
	var tenant_id int64
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
